---
version: '3'

services:
  backend:
    container_name: "cloud-course-backend"
    image: cloud-go-backend
    build:
      context: backend
    restart: always
    ports:
      - "5000:5000"
  frontend:
    container_name: "cloud-course-frontend"
    image: nginx
    volumes:
      - "./frontend/static:/usr/share/nginx/html:ro"
    ports:
      - "3000:80"
    depends_on:
      - backend
