---
version: '3'

services:
  backend:
    container_name: "cloud-course-backend"
    image: gabrielivarsson/calc-business-logic-server:latest
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - GIN_MODE=release
